name: PR Docker builder
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      env:
        ECR_REPOSITORY: portal
        IMAGE_TAG: ${{ github.sha }}
        RAILS_ENV: production
      run: |
        docker build -t covidshield.app/ci/$ECR_REPOSITORY:$IMAGE_TAG .
    - name: Container security scan
      uses: Azure/container-scan@v0
      with:
        image-name: covidshield.app/ci/portal:${{ github.sha }}
