name: Dockerhub Container Builds

on:
  push:
    branches: [ master ]

jobs:
  build-n-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Portal
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: covidshield/portal
        tags: latest,${{ github.sha }}
