name: 'Terraform'

on:
  push:
    branches:
    - master
  pull_request:
    paths:
    - 'config/terraform/aws/*'

defaults:
  run:
    shell: bash
    working-directory: config/terraform/aws

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ca-central-1
  TF_VAR_ecs_task_portal_env_rails_master_key: ${{ secrets.TF_VAR_ecs_task_portal_env_rails_master_key }}
  TF_VAR_rds_portal_db_password: ${{ secrets.TF_VAR_rds_portal_db_password }}

jobs:
  terraform-plan:
    if: github.repository_owner == 'CovidShield'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan

  terraform-apply:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push' && github.repository_owner == 'CovidShield'
    runs-on: ubuntu-latest
    steps:
    - name: Wait for container to be built and pushed
      uses: fountainhead/action-wait-for-check@v1.0.0
      id: wait-for-build
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: build-n-push
        ref: ${{ github.sha }}

    - name: Checkout
      if: steps.wait-for-build.outputs.conclusion == 'success'
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan -out terraform.tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve terraform.tfplan
